# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 750e9a7cba17d99914571b52203ea3bbe75c1494da5cb062ef2a332699dd80d479ea2ba4e26a3674fb974922cc0bffb00ace523c9eef99d9ffa80be2fc6e8e9d

test:
  secret_key_base: 377597cc50d8c80002c7e54fffb6b0aacb32e161b30251eb34865928b76c309b898133236659a00cf56f29d8e419240a4390ab9ad39434016d1a6560103a4d6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
